---
- hosts: "{{ instance_name }}"
  vars:
    ansible_port: "{{ hostvars[instance_name]['openstack']['metadata'].ssh_pub_port }}"
    ansible_host: "{{ hostvars[instance_name]['openstack']['metadata'].ssh_pub_ip }}"
    ansible_user: "{{ default_username }}"
  roles:
    - hoplacloud.linux_base_add_user

- hosts: "{{ instance_name }}"
  vars:
    ansible_port: "{{ hostvars[instance_name]['openstack']['metadata'].ssh_pub_port }}"
    ansible_host: "{{ hostvars[instance_name]['openstack']['metadata'].ssh_pub_ip }}"
  roles:
    - hoplacloud.linux_base_del_user
