---
- hosts: localhost
  gather_facts: no
  tasks:
     - shell: |
            echo "{{ private_key }}" > private_key.pem
            nova get-password h9999ad1 private_key.pem
            rm -f private_key
