---
- hosts: localhost
  gather_facts: no
  tasks:
     - os_auth:
     - uri:
         url: "https://fr-east-1.pub.hopla.cloud:13774/v2.1/servers/f61307c6-c049-4371-ad83-d059d1c8e635/os-server-password"
         headers:
           Content-Type: "application/json"
           X-Auth-Token: "{{ auth_token }}"
       register: password_crypt
     - shell: echo "{{ private_key }}" > private_key.pem

     - shell: |
        echo "{{ password_crypt.json.password }}" \
        | openssl base64 -d \
        | openssl rsautl -decrypt -inkey private_key.pem -keyform PEM
