---
- name: Configure en_US.UTF-8 locale
  locale_gen:
    name: en_US.UTF-8
    state: present
    
- name: Ensure password ssh authentification is yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication yes"

- name: restart service ssh
  systemd:
    state: restarted
    name: ssh

- name: Set timezone to Europe/Paris
  timezone:
    name: Europe/Paris

- name: Ensure keyboard is fr
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT'
    line: 'XKBLAYOUT="fr"'

- name: restart service keyboard
  systemd:
    state: restarted
    name: keyboard-setup
