---
- name: Kill SSH
  shell: sleep 1; pkill -u {{ default_username }} sshd
  async: 3
  poll: 2
  ignore_errors: True

- name: Pause
  pause:
    seconds: 30
- name: Delete delfaut SUDO user
  user:
    name: "{{ default_username }}"
    comment: "Default sudo user created by hopla.cloud"
    state: absent
    remove: yes

- name: Check if the Hopla.cloud sudo rule exists
  stat:
    path: /etc/sudoers.d/90-Hoplacloud-sudo-users
  register: stat_sudo

- name: Remove delfaut sudo rule
  file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent
  when: stat_sudo.stat.exists == False

- name: Ensure password ssh authentification is yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication yes"

- name: restart service ssh
  systemd:
    state: restarted
    name: ssh

- name: Set timezone to Europe/Paris
  timezone:
    name: Europe/Paris

- name: Ensure keyboard is fr
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^XKBLAYOUT'
    line: 'XKBLAYOUT="fr"'

- name: restart service keyboard
  systemd:
    state: restarted
    name: keyboard-setup
